{% set name = "iterative-telemetry" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 53686c3e912a33e8bf6975b878fd4bd0a7d589c8bad0a6a5573714af9e731dc2

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<38]

requirements:
  host:
    - python
    - pip
    - setuptools_scm >=6.3.1
    - wheel
  run:
    - python
    - requests
    - appdirs
    - filelock
    - distro

test:
  source_files:
    - tests
  imports:
    - iterative_telemetry
  requires:
    - pip
    - pytest
    - pytest-mock
  commands:
    - pip check
    - pytest -vv tests

about:
  home: https://github.com/iterative/telemetry-python
  summary: Common library to send usage telemetry
  description: |
    Common library to send usage telemetry,
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://github.com/iterative/telemetry-python/blob/main/README.rst
  dev_url: https://github.com/iterative/telemetry-python

extra:
  recipe-maintainers:
    - pmrowla
    - shcheklein
    - casperdcl
    - mike0sv
